#    ___                      _     ___  ___  ___
#   / __\___  _ __  ___ _   _| |   / _ \/___\/ __\
#  / /  / _ \| '_ \/ __| | | | |  / /_)//  // /
# / /__| (_) | | | \__ \ |_| | | / ___/ \_// /___
# \____/\___/|_| |_|___/\__,_|_| \/   \___/\____/
#
# Consul Network proof of concept
# (c) 2018 Adam K Dean

version: "3.5"

services:
  consult-agent:
    image: "library/consul:1.0.7"
    container_name: consul-agent-1
    hostname: consul-agent-1
    networks:
      - test-network
    command: "agent -retry-join consul-server -client 0.0.0.0"

  gateway1:
    image: "local/consul-poc/gateway:latest"
    container_name: gateway1
    hostname: gateway1
    environment:
      - CONSUL_ADDRESS=consul-agent-1:8500
      - LISTEN_PORT=8000
    networks:
      - test-network

  gateway2:
    image: "local/consul-poc/gateway:latest"
    container_name: gateway2
    hostname: gateway2
    environment:
      - CONSUL_ADDRESS=consul-agent-1:8500
      - LISTEN_PORT=8000
    networks:
      - test-network

networks:
  test-network:
    external: true
    name: global
