#    ___                      _     ___  ___  ___
#   / __\___  _ __  ___ _   _| |   / _ \/___\/ __\
#  / /  / _ \| '_ \/ __| | | | |  / /_)//  // /
# / /__| (_) | | | \__ \ |_| | | / ___/ \_// /___
# \____/\___/|_| |_|___/\__,_|_| \/   \___/\____/
#
# Consul Network proof of concept
# (c) 2018 Adam K Dean

version: "3.5"

services:
  consul-server:
    image: "library/consul:1.0.7"
    container_name: consul-server
    hostname: consul-server
    networks:
      - test-network
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap -ui -client 0.0.0.0"

  stargate:
    image: "local/consul-poc/stargate:latest"
    container_name: stargate
    hostname: stargate
    environment:
      - CONSUL_ADDRESS=consul-server:8500
    networks:
      - test-network

networks:
  test-network:
    external: true
    name: global
