#    ___                      _     ___  ___  ___
#   / __\___  _ __  ___ _   _| |   / _ \/___\/ __\
#  / /  / _ \| '_ \/ __| | | | |  / /_)//  // /
# / /__| (_) | | | \__ \ |_| | | / ___/ \_// /___
# \____/\___/|_| |_|___/\__,_|_| \/   \___/\____/
#
# Consul Network proof of concept
# (c) 2018 Adam K Dean

version: "3"

services:
  consult-agent-1: &consul-agent
    image: "library/consul:1.0.7"
    hostname: agent1.consul.local
    networks:
      - consul_network
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent
    hostname: agent2.consul.local

  consul-agent-3:
    <<: *consul-agent
    hostname: agent3.consul.local

  consul-server-1: &consul-server
    <<: *consul-agent
    hostname: server1.consul.local
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server
    hostname: server2.consul.local

  consul-server-bootstrap:
    <<: *consul-agent
    hostname: server3.consul.local
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul_network:
